-- Benthyo seed data (idempotent)
-- 50 Mediterranean dive sites, 200 marine species, 5 Italian operators, 10 badges

BEGIN;

INSERT INTO dive_sites (name, slug, description, location, country_code, region, depth_min, depth_max, difficulty, site_type, access_type, verified, metadata)
VALUES
  ('Ustica Secca della Colobbara', 'ustica-secca-colobbara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.18, 38.71), 4326)::geography, 'IT', 'Sicily', 5, 45, 'advanced', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ustica Secca di Punta Gavazzi', 'ustica-punta-gavazzi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.175, 38.695), 4326)::geography, 'IT', 'Sicily', 8, 50, 'advanced', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ustica Grotta dei Gamberi', 'ustica-grotta-gamberi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.19, 38.7), 4326)::geography, 'IT', 'Sicily', 10, 35, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Portofino Christ of the Abyss', 'portofino-cristo-abissi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.2167, 44.3167), 4326)::geography, 'IT', 'Liguria', 12, 18, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Portofino Punta del Faro', 'portofino-punta-faro', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.21, 44.303), 4326)::geography, 'IT', 'Liguria', 15, 40, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Elba Pomonte Wreck', 'elba-pomonte-wreck', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(10.12, 42.745), 4326)::geography, 'IT', 'Tuscany', 12, 18, 'beginner', 'wreck', 'shore', true, '{"seed": true}'::jsonb),
  ('Elba Scoglietto di Portoferraio', 'elba-scoglietto', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(10.32, 42.815), 4326)::geography, 'IT', 'Tuscany', 5, 25, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Sardinia Tavolara Punta Timi', 'sardinia-tavolara-timi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.72, 40.91), 4326)::geography, 'IT', 'Sardinia', 10, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Sardinia Capo Carbonara', 'sardinia-capo-carbonara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.52, 39.1), 4326)::geography, 'IT', 'Sardinia', 5, 30, 'beginner', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Sardinia Nora Roman Ruins', 'sardinia-nora-ruins', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.01, 39), 4326)::geography, 'IT', 'Sardinia', 3, 12, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Lampedusa Secchitello', 'lampedusa-secchitello', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(12.61, 35.52), 4326)::geography, 'IT', 'Pelagie Islands', 15, 50, 'advanced', 'pinnacle', 'boat', true, '{"seed": true}'::jsonb),
  ('Lampedusa Tabaccara', 'lampedusa-tabaccara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(12.6, 35.5), 4326)::geography, 'IT', 'Pelagie Islands', 5, 20, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Pantelleria Grotta di Sataria', 'pantelleria-sataria', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(11.95, 36.83), 4326)::geography, 'IT', 'Sicily', 5, 15, 'beginner', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Ischia Secca delle Formiche', 'ischia-formiche', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.95, 40.73), 4326)::geography, 'IT', 'Campania', 10, 40, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Procida Vivara Island', 'procida-vivara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.02, 40.76), 4326)::geography, 'IT', 'Campania', 5, 25, 'beginner', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ponza Secca di Frontone', 'ponza-frontone', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(12.96, 40.91), 4326)::geography, 'IT', 'Lazio', 8, 35, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ventotene Secca di Santo Stefano', 'ventotene-santo-stefano', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.43, 40.8), 4326)::geography, 'IT', 'Lazio', 10, 45, 'advanced', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Capri Blue Grotto Area', 'capri-blue-grotto', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.21, 40.56), 4326)::geography, 'IT', 'Campania', 5, 30, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Sorrento Bagni della Regina', 'sorrento-bagni-regina', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.38, 40.63), 4326)::geography, 'IT', 'Campania', 5, 20, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Amalfi Li Galli', 'amalfi-li-galli', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.25, 40.55), 4326)::geography, 'IT', 'Campania', 15, 40, 'advanced', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Cilento Punta Licosa', 'cilento-licosa', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.9, 40.25), 4326)::geography, 'IT', 'Campania', 8, 30, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Tremiti San Domino', 'tremiti-san-domino', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(15.5, 42.12), 4326)::geography, 'IT', 'Puglia', 5, 35, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Otranto Punta Palascia', 'otranto-palascia', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(18.51, 40.13), 4326)::geography, 'IT', 'Puglia', 5, 25, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Gallipoli Molo di San Andrea', 'gallipoli-san-andrea', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(17.99, 40.05), 4326)::geography, 'IT', 'Puglia', 3, 15, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Cirkewwa Reef', 'malta-cirkewwa', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.33, 35.99), 4326)::geography, 'MT', 'Malta', 5, 30, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Um El Faroud Wreck', 'malta-um-el-faroud', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.54, 35.82), 4326)::geography, 'MT', 'Malta', 18, 35, 'intermediate', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('Malta Blue Hole Gozo', 'malta-blue-hole-gozo', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.19, 36.055), 4326)::geography, 'MT', 'Gozo', 5, 40, 'intermediate', 'wall', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Inland Sea', 'malta-inland-sea', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.185, 36.052), 4326)::geography, 'MT', 'Gozo', 5, 25, 'intermediate', 'wall', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Reqqa Point', 'malta-reqqa-point', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.23, 36.08), 4326)::geography, 'MT', 'Gozo', 10, 45, 'advanced', 'wall', 'shore', true, '{"seed": true}'::jsonb),
  ('Croatia Vis Blue Cave', 'croatia-vis-blue-cave', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(16.04, 43.05), 4326)::geography, 'HR', 'Vis', 5, 20, 'beginner', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Bisevo Blue Cave', 'croatia-bisevo-blue-cave', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(16.04, 42.98), 4326)::geography, 'HR', 'Vis', 5, 15, 'beginner', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Taranto Wreck', 'croatia-taranto-wreck', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(16.44, 43.17), 4326)::geography, 'HR', 'Hvar', 20, 42, 'advanced', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Premuda Cathedral', 'croatia-premuda-cathedral', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.6, 44.33), 4326)::geography, 'HR', 'Premuda', 15, 50, 'advanced', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Kornati Mana', 'croatia-kornati-mana', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(15.35, 43.79), 4326)::geography, 'HR', 'Kornati', 5, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Zakynthos Keri Caves', 'greece-zakynthos-keri', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(20.82, 37.68), 4326)::geography, 'GR', 'Ionian Islands', 5, 25, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Mykonos Paradise Reef', 'greece-mykonos-paradise', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(25.35, 37.42), 4326)::geography, 'GR', 'Cyclades', 5, 30, 'beginner', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Santorini Nea Kameni', 'greece-santorini-nea-kameni', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(25.4, 36.4), 4326)::geography, 'GR', 'Cyclades', 10, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Crete Elephant Cave', 'greece-crete-elephant-cave', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(24.25, 35.42), 4326)::geography, 'GR', 'Crete', 8, 20, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Rhodes Anthony Quinn Bay', 'greece-rhodes-anthony-quinn', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(28.23, 36.44), 4326)::geography, 'GR', 'Dodecanese', 5, 25, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Spain Medes Islands Tasco Petit', 'spain-medes-tasco-petit', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(3.22, 42.05), 4326)::geography, 'ES', 'Catalonia', 10, 35, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Spain Cabo de Palos Isla Hormiga', 'spain-cabo-palos-hormiga', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(-0.68, 37.63), 4326)::geography, 'ES', 'Murcia', 10, 45, 'advanced', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Spain Cabo de Gata La Foradada', 'spain-cabo-gata-foradada', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(-2.19, 36.72), 4326)::geography, 'ES', 'Andalusia', 5, 20, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Spain Ibiza Don Pedro Wreck', 'spain-ibiza-don-pedro', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(1.42, 38.88), 4326)::geography, 'ES', 'Balearic Islands', 25, 45, 'advanced', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('France Port-Cros La Gabinière', 'france-port-cros-gabiniere', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(6.39, 43.01), 4326)::geography, 'FR', 'Var', 10, 40, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('France Cerbère Banyuls Reserve', 'france-cerbere-banyuls', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(3.16, 42.44), 4326)::geography, 'FR', 'Occitanie', 5, 30, 'intermediate', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('France Marseille Les Catalans', 'france-marseille-catalans', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(5.36, 43.29), 4326)::geography, 'FR', 'Provence', 5, 25, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('France Nice Cap Ferrat', 'france-nice-cap-ferrat', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(7.33, 43.69), 4326)::geography, 'FR', 'Alpes-Maritimes', 10, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Monaco Larvotto Reserve', 'monaco-larvotto', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(7.43, 43.75), 4326)::geography, 'MC', 'Monaco', 8, 30, 'intermediate', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Cyprus Zenobia Wreck', 'cyprus-zenobia', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(33.65, 34.89), 4326)::geography, 'CY', 'Larnaca', 16, 42, 'advanced', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('Egypt Ras Mohammed Shark Reef', 'egypt-ras-mohammed', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(34.25, 27.73), 4326)::geography, 'EG', 'Sinai', 5, 40, 'advanced', 'wall', 'boat', true, '{"seed": true}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  depth_min = EXCLUDED.depth_min,
  depth_max = EXCLUDED.depth_max,
  updated_at = now();

INSERT INTO species (scientific_name, common_name, common_name_it, common_name_es, family, genus, inat_taxon_id, worms_id, gbif_taxon_key, kingdom, metadata)
VALUES
  ('Epinephelus marginatus', 'Dusky grouper', 'Cernia bruna', 'Mero', 'Serranidae', 'Epinephelus', 492851, 274059, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Thalassoma pavo', 'Ornate wrasse', 'Tordo pavone', 'Pez verde', 'Labridae', 'Thalassoma', 458521, 273370, 273370, 'Animalia', '{"seed": true}'::jsonb),
  ('Sparisoma cretense', 'Parrotfish', 'Pesce pappagallo', 'Pez loro', 'Scaridae', 'Sparisoma', 458514, 273374, 273374, 'Animalia', '{"seed": true}'::jsonb),
  ('Coris julis', 'Mediterranean rainbow wrasse', 'Tordo', 'Doncella', 'Labridae', 'Coris', 458475, 273368, 273368, 'Animalia', '{"seed": true}'::jsonb),
  ('Chromis chromis', 'Damselfish', 'Castagnola', 'Castañuela', 'Pomacentridae', 'Chromis', 458463, 273366, 273366, 'Animalia', '{"seed": true}'::jsonb),
  ('Anthias anthias', 'Swallowtail seaperch', 'Anthias', 'Breca', 'Serranidae', 'Anthias', 458452, 273364, 273364, 'Animalia', '{"seed": true}'::jsonb),
  ('Sciaena umbra', 'Brown meagre', 'Corvina', 'Corvina', 'Sciaenidae', 'Sciaena', 492855, 274063, 274063, 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus sargus', 'White seabream', 'Sarago maggiore', 'Sargo', 'Sparidae', 'Diplodus', 458468, 273367, 273367, 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus vulgaris', 'Two-banded seabream', 'Sarago comune', 'Sargo común', 'Sparidae', 'Diplodus', 458469, 273367, 273367, 'Animalia', '{"seed": true}'::jsonb),
  ('Sarpa salpa', 'Salema', 'Salpa', 'Salpa', 'Sparidae', 'Sarpa', 458513, 273373, 273373, 'Animalia', '{"seed": true}'::jsonb),
  ('Boops boops', 'Bogue', 'Tanuta', 'Boga', 'Sparidae', 'Boops', 458456, 273365, 273365, 'Animalia', '{"seed": true}'::jsonb),
  ('Oblada melanura', 'Saddled seabream', 'Oblada', 'Chopa', 'Sparidae', 'Oblada', 458502, 273371, 273371, 'Animalia', '{"seed": true}'::jsonb),
  ('Pagellus erythrinus', 'Common pandora', 'Pagello', 'Pargo', 'Sparidae', 'Pagellus', 458505, 273372, 273372, 'Animalia', '{"seed": true}'::jsonb),
  ('Lithognathus mormyrus', 'Striped seabream', 'Mormora', 'Mormora', 'Sparidae', 'Lithognathus', 458491, 273369, 273369, 'Animalia', '{"seed": true}'::jsonb),
  ('Symphodus tinca', 'Peacock wrasse', 'Tordo verde', 'Doncella', 'Labridae', 'Symphodus', 458518, 273375, 273375, 'Animalia', '{"seed": true}'::jsonb),
  ('Labrus merula', 'Brown wrasse', 'Tordo nero', 'Doncella', 'Labridae', 'Labrus', 458487, 273368, 273368, 'Animalia', '{"seed": true}'::jsonb),
  ('Xyrichtys novacula', 'Pearly razorfish', 'Pesce luna', 'Pez ballesta', 'Labridae', 'Xyrichtys', 458524, 273376, 273376, 'Animalia', '{"seed": true}'::jsonb),
  ('Centrolabrus trutta', 'Small-mouth wrasse', 'Tordo piccolo', 'Doncella', 'Labridae', 'Centrolabrus', 458461, 273366, 273366, 'Animalia', '{"seed": true}'::jsonb),
  ('Mullus surmuletus', 'Striped red mullet', 'Triglia di fango', 'Salmonete', 'Mullidae', 'Mullus', 458498, 273370, 273370, 'Animalia', '{"seed": true}'::jsonb),
  ('Mullus barbatus', 'Red mullet', 'Triglia', 'Salmonete', 'Mullidae', 'Mullus', 458497, 273370, 273370, 'Animalia', '{"seed": true}'::jsonb),
  ('Trachinus draco', 'Greater weever', 'Pesce scorpione', 'Pez araña', 'Trachinidae', 'Trachinus', 458519, 273375, 273375, 'Animalia', '{"seed": true}'::jsonb),
  ('Uranoscopus scaber', 'Stargazer', 'Ragno di mare', 'Pez rata', 'Uranoscopidae', 'Uranoscopus', 458521, 273376, 273376, 'Animalia', '{"seed": true}'::jsonb),
  ('Scomber scombrus', 'Atlantic mackerel', 'Sgombro', 'Caballa', 'Scombridae', 'Scomber', 492860, 274068, 274068, 'Animalia', '{"seed": true}'::jsonb),
  ('Sarda sarda', 'Atlantic bonito', 'Palamita', 'Bonito', 'Scombridae', 'Sarda', 492858, 274066, 274066, 'Animalia', '{"seed": true}'::jsonb),
  ('Thunnus thynnus', 'Bluefin tuna', 'Tonno rosso', 'Atún rojo', 'Scombridae', 'Thunnus', 492862, 274070, 274070, 'Animalia', '{"seed": true}'::jsonb),
  ('Belone belone', 'Garfish', 'Aguglia', 'Aguja', 'Belonidae', 'Belone', 458455, 273365, 273365, 'Animalia', '{"seed": true}'::jsonb),
  ('Fistularia commersonii', 'Red cornetfish', 'Fistularia', 'Pez pipa', 'Fistulariidae', 'Fistularia', 458471, 145063, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Syngnathus abaster', 'Pipefish', 'Pesce ago', 'Pez pipa', 'Syngnathidae', 'Syngnathus', 458517, 145149, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Hippocampus hippocampus', 'Short-snouted seahorse', 'Cavalluccio marino', 'Caballito de mar', 'Syngnathidae', 'Hippocampus', 458479, 145148, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Octopus vulgaris', 'Common octopus', 'Polpo', 'Pulpo', 'Octopodidae', 'Octopus', 458503, 145147, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sepia officinalis', 'Common cuttlefish', 'Seppia', 'Sepia', 'Sepiidae', 'Sepia', 458515, 145146, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sepiola atlantica', 'Little cuttlefish', 'Sepiola', 'Sepiola', 'Sepiolidae', 'Sepiola', 458516, 145145, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Loligo vulgaris', 'European squid', 'Calamaro', 'Calamar', 'Loliginidae', 'Loligo', 458490, 145144, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Eledone moschata', 'Musky octopus', 'Polpo muschiato', 'Pulpo almizclero', 'Octopodidae', 'Eledone', 458470, 145143, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Palinurus elephas', 'Spiny lobster', 'Aragosta', 'Langosta', 'Palinuridae', 'Palinurus', 458506, 145141, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Homarus gammarus', 'European lobster', 'Astice', 'Bogavante', 'Nephropidae', 'Homarus', 458478, 145142, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Scyllarides latus', 'Slipper lobster', 'Cicale di mare', 'Cigarra de mar', 'Scyllaridae', 'Scyllarides', 458512, 145140, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Maja squinado', 'Spider crab', 'Granchio ragno', 'Centollo', 'Majidae', 'Maja', 458492, 145139, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pachygrapsus marmoratus', 'Marbled rock crab', 'Granchio di scoglio', 'Cangrejo', 'Grapsidae', 'Pachygrapsus', 458504, 145138, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Carcinus maenas', 'Green crab', 'Granchio verde', 'Cangrejo verde', 'Carcinidae', 'Carcinus', 458459, 273366, 273366, 'Animalia', '{"seed": true}'::jsonb),
  ('Paracentrotus lividus', 'Purple sea urchin', 'Riccio di mare', 'Erizo de mar', 'Parechinidae', 'Paracentrotus', 458505, 273372, 273372, 'Animalia', '{"seed": true}'::jsonb),
  ('Arbacia lixula', 'Black sea urchin', 'Riccio nero', 'Erizo negro', 'Arbaciidae', 'Arbacia', 458451, 273364, 273364, 'Animalia', '{"seed": true}'::jsonb),
  ('Astroides calycularis', 'Orange coral', 'Astroides', 'Coral naranja', 'Dendrophylliidae', 'Astroides', 458453, 273364, 273364, 'Animalia', '{"seed": true}'::jsonb),
  ('Paramuricea clavata', 'Red gorgonian', 'Gorgonia rossa', 'Gorgonia roja', 'Paramuriceidae', 'Paramuricea', 458507, 273372, 273372, 'Animalia', '{"seed": true}'::jsonb),
  ('Eunicella singularis', 'White gorgonian', 'Gorgonia bianca', 'Gorgonia blanca', 'Gorgoniidae', 'Eunicella', 458472, 273367, 273367, 'Animalia', '{"seed": true}'::jsonb),
  ('Antipathella subpinnata', 'Yellow black coral', 'Corallo nero', 'Coral negro', 'Myriopathidae', 'Antipathella', 458450, 273364, 273364, 'Animalia', '{"seed": true}'::jsonb),
  ('Cladocora caespitosa', 'Mediterranean pillow coral', 'Madrepora a cuscino', 'Coral cojín', 'Cladocoridae', 'Cladocora', 458464, 273366, 273366, 'Animalia', '{"seed": true}'::jsonb),
  ('Corynactis viridis', 'Strawberry anemone', 'Anemone fragola', 'Anémona fresa', 'Corallimorphidae', 'Corynactis', 458466, 273366, 273366, 'Animalia', '{"seed": true}'::jsonb),
  ('Anemonia viridis', 'Snakelocks anemone', 'Anemone di mare', 'Anémona de mar', 'Actiniidae', 'Anemonia', 458449, 273364, 273364, 'Animalia', '{"seed": true}'::jsonb),
  ('Actinia equina', 'Beadlet anemone', 'Anemone rossa', 'Anémona roja', 'Actiniidae', 'Actinia', 458448, 273364, 273364, 'Animalia', '{"seed": true}'::jsonb),
  ('Cerianthus membranaceus', 'Tube anemone', 'Ceriantho', 'Ceriantho', 'Cerianthidae', 'Cerianthus', 458460, 127010, 5279, 'Animalia', '{"seed": true}'::jsonb),
  ('Scorpaena scrofa', 'Red scorpionfish', 'Scorfano rosso', 'Rascacio', 'Scorpaenidae', 'Scorpaena', 492856, 127692, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Scorpaena porcus', 'Black scorpionfish', 'Scorfano nero', 'Rascacio', 'Scorpaenidae', 'Scorpaena', 458510, 127693, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Apogon imberbis', 'Cardinalfish', 'Cardinale', 'Cardinal', 'Apogonidae', 'Apogon', 458448, 127580, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Conger conger', 'European conger', 'Grongo', 'Congrio', 'Congridae', 'Conger', 458465, 127370, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Muraena helena', 'Mediterranean moray', 'Murena', 'Morena', 'Muraenidae', 'Muraena', 458499, 127404, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Gymnothorax unicolor', 'Mediterranean moray', 'Murena', 'Morena', 'Muraenidae', 'Gymnothorax', 458479, 127405, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Serranus cabrilla', 'Comber', 'Perchia', 'Serrano', 'Serranidae', 'Serranus', 458513, 127411, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Serranus scriba', 'Painted comber', 'Perchia', 'Serrano', 'Serranidae', 'Serranus', 458514, 127412, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Epinephelus costae', 'Goldblotch grouper', 'Cernia maculata', 'Mero', 'Serranidae', 'Epinephelus', 492850, 127410, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Mycteroperca rubra', 'Mottled grouper', 'Cernia rossa', 'Mero', 'Serranidae', 'Mycteroperca', 458500, 127409, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Balistes capriscus', 'Grey triggerfish', 'Balestra', 'Pez ballesta', 'Balistidae', 'Balistes', 458454, 127350, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Dentex dentex', 'Common dentex', 'Dentice', 'Denton', 'Sparidae', 'Dentex', 458468, 127300, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pagrus pagrus', 'Red porgy', 'Pagro', 'Pagre', 'Sparidae', 'Pagrus', 458506, 127301, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Seriola dumerili', 'Greater amberjack', 'Ricciola', 'Serviola', 'Carangidae', 'Seriola', 458513, 127320, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sphyraena sphyraena', 'European barracuda', 'Barracuda', 'Barracuda', 'Sphyraenidae', 'Sphyraena', 458515, 127330, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Zeus faber', 'John Dory', 'Pesce San Pietro', 'Pez de San Pedro', 'Zeidae', 'Zeus', 458524, 127340, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Xiphias gladius', 'Swordfish', 'Pesce spada', 'Pez espada', 'Xiphiidae', 'Xiphias', 458524, 127341, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Merluccius merluccius', 'European hake', 'Nasello', 'Merluza', 'Merlucciidae', 'Merluccius', 458494, 127350, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Engraulis encrasicolus', 'European anchovy', 'Acciuga', 'Anchoa', 'Engraulidae', 'Engraulis', 458470, 127360, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sardina pilchardus', 'Sardine', 'Sardina', 'Sardina', 'Clupeidae', 'Sardina', 458511, 127361, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Chelonia mydas', 'Green sea turtle', 'Tartaruga verde', 'Tortuga verde', 'Cheloniidae', 'Chelonia', 458463, 137205, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Caretta caretta', 'Loggerhead sea turtle', 'Tartaruga caretta', 'Tortuga boba', 'Cheloniidae', 'Caretta', 458459, 137206, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Tursiops truncatus', 'Bottlenose dolphin', 'Tursiope', 'Delfin mular', 'Delphinidae', 'Tursiops', 458520, 137207, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Monachus monachus', 'Mediterranean monk seal', 'Foca monaca', 'Foca monje', 'Phocidae', 'Monachus', 458496, 137208, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Torpedo marmorata', 'Marbled electric ray', 'Triglia di mare', 'Raya electrica', 'Torpedinidae', 'Torpedo', 458519, 127500, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Raja clavata', 'Thornback ray', 'Razza chiodata', 'Raya', 'Rajidae', 'Raja', 458509, 127501, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Myliobatis aquila', 'Common eagle ray', 'Pastinaca aquila', 'Aguila marmorea', 'Myliobatidae', 'Myliobatis', 458498, 127502, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Squatina squatina', 'Angelshark', 'Squalo angelo', 'Tiburon angel', 'Squatinidae', 'Squatina', 458516, 127503, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Galeus melastomus', 'Blackmouth catshark', 'Gattuccio', 'Gato marino', 'Scyliorhinidae', 'Galeus', 458473, 127504, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Scyliorhinus stellaris', 'Nursehound', 'Gattuccio maculato', 'Gato marino', 'Scyliorhinidae', 'Scyliorhinus', 458512, 127505, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Mustelus mustelus', 'Smooth-hound', 'Verdesca', 'Tiburon', 'Triakidae', 'Mustelus', 458499, 127506, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Mobula mobular', 'Giant devil ray', 'Manta', 'Manta', 'Mobulidae', 'Mobula', 458495, 127507, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Posidonia oceanica', 'Neptune grass', 'Posidonia', 'Posidonia', 'Posidoniaceae', 'Posidonia', 458509, 145000, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Cymodocea nodosa', 'Little Neptune grass', 'Cymodocea', 'Cymodocea', 'Cymodoceaceae', 'Cymodocea', 458467, 145001, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Caulerpa taxifolia', 'Killer algae', 'Caulerpa', 'Caulerpa', 'Caulerpaceae', 'Caulerpa', 458460, 145002, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Corallina officinalis', 'Coral weed', 'Corallina', 'Corallina', 'Corallinaceae', 'Corallina', 458465, 145003, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pelagia noctiluca', 'Mauve stinger', 'Pelagia', 'Medusa', 'Pelagiidae', 'Pelagia', 458507, 145004, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Aurelia aurita', 'Moon jellyfish', 'Medusa lunare', 'Medusa lunar', 'Ulmaridae', 'Aurelia', 458453, 145005, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Rhizostoma pulmo', 'Barrel jellyfish', 'Medusa', 'Medusa', 'Rhizostomatidae', 'Rhizostoma', 458510, 145006, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Cotylorhiza tuberculata', 'Fried egg jellyfish', 'Medusa uovo', 'Medusa huevo frito', 'Cepheidae', 'Cotylorhiza', 458466, 145007, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Flabellina affinis', 'Purple nudibranch', 'Nudibranch', 'Nudibranquio', 'Flabellinidae', 'Flabellina', 458471, 145008, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Felimare picta', 'Painted nudibranch', 'Nudibranch', 'Nudibranquio', 'Chromodorididae', 'Felimare', 458471, 145009, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Cratena peregrina', 'Peregrine aeolid', 'Nudibranch', 'Nudibranquio', 'Fionidae', 'Cratena', 458466, 145010, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Aplysia fasciata', 'Mottled sea hare', 'Lepre di mare', 'Liebre de mar', 'Aplysiidae', 'Aplysia', 458447, 145011, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Bursatella leachii', 'Ragged sea hare', 'Lepre di mare', 'Liebre de mar', 'Aplysiidae', 'Bursatella', 458458, 145012, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Ophioderma longicaudum', 'Brittle star', 'Ofiura', 'Ofiura', 'Ophiodermatidae', 'Ophioderma', 458502, 145013, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Antedon mediterranea', 'Feather star', 'Comatula', 'Estrella pluma', 'Antedonidae', 'Antedon', 458449, 145014, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Marthasterias glacialis', 'Spiny starfish', 'Stella marina spinosa', 'Estrella de mar', 'Asteriidae', 'Marthasterias', 458493, 145015, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Echinaster sepositus', 'Red starfish', 'Stella rossa', 'Estrella roja', 'Echinasteridae', 'Echinaster', 458469, 145016, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sphaerechinus granularis', 'Purple sea urchin', 'Riccio viola', 'Erizo violeta', 'Toxopneustidae', 'Sphaerechinus', 458515, 145017, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Holothuria tubulosa', 'Sea cucumber', 'Carciofo di mare', 'Pepino de mar', 'Holothuriidae', 'Holothuria', 458478, 145018, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Holothuria forskali', 'Black sea cucumber', 'Carciofo nero', 'Pepino de mar', 'Holothuriidae', 'Holothuria', 458476, 145019, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Spondylus gaederopus', 'Thorny oyster', 'Spondilo', 'Ostra espinosa', 'Spondylidae', 'Spondylus', 458516, 145020, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Charonia tritonis', 'Triton trumpet', 'Tritone', 'Triton', 'Charoniidae', 'Charonia', 458462, 145021, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Hexaplex trunculus', 'Dye-murex', 'Murice', 'Canailia', 'Muricidae', 'Hexaplex', 458477, 145022, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Haliotis tuberculata', 'Ormer', 'Orecchia di mare', 'Oreja de mar', 'Haliotidae', 'Haliotis', 458476, 145023, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pinna nobilis', 'Noble pen shell', 'Pinna', 'Nacra', 'Pinnidae', 'Pinna', 458510, 145024, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Mytilus galloprovincialis', 'Mediterranean mussel', 'Cozza', 'Mejillon', 'Mytilidae', 'Mytilus', 458499, 145025, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Spongia officinalis', 'Bath sponge', 'Spugna', 'Esponja', 'Spongiidae', 'Spongia', 458516, 145026, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Axinella polypoides', 'Yellow horn sponge', 'Spugna cornuta', 'Esponja', 'Axinellidae', 'Axinella', 458454, 145027, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Petrosia ficiformis', 'Elephant ear sponge', 'Spugna orecchia', 'Esponja', 'Petrosiidae', 'Petrosia', 458509, 145028, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Aplysina aerophoba', 'Yellow sponge', 'Spugna gialla', 'Esponja amarilla', 'Aplysinidae', 'Aplysina', 458447, 145029, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Gobius niger', 'Black goby', 'Gobio nero', 'Gobio negro', 'Gobiidae', 'Gobius', 458474, 145030, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Gobius cruentatus', 'Red-mouth goby', 'Gobio', 'Gobio', 'Gobiidae', 'Gobius', 458473, 145031, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Parablennius gattorugine', 'Tompot blenny', 'Blennio', 'Blenio', 'Blenniidae', 'Parablennius', 458506, 145032, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Tripterygion delaisi', 'Red-black triplefin', 'Tripterigione', 'Tripterigion', 'Tripterygiidae', 'Tripterygion', 458520, 145033, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Ctenolabrus rupestris', 'Goldsinny wrasse', 'Tordo', 'Doncella', 'Labridae', 'Ctenolabrus', 458467, 145034, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Symphodus roissali', 'Five-spotted wrasse', 'Tordo', 'Doncella', 'Labridae', 'Symphodus', 458518, 145035, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Symphodus ocellatus', 'Ocellated wrasse', 'Tordo', 'Doncella', 'Labridae', 'Symphodus', 458517, 145036, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Crenilabrus ocellatus', 'Ocellated wrasse', 'Tordo', 'Doncella', 'Labridae', 'Crenilabrus', 458466, 145037, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Solea solea', 'Common sole', 'Sogliola', 'Lenguado', 'Soleidae', 'Solea', 458515, 145038, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Bothus podas', 'Wide-eyed flounder', 'Passera', 'Lenguado', 'Bothidae', 'Bothus', 458457, 145039, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Scophthalmus rhombus', 'Brill', 'Rombo chiodato', 'Rodaballo', 'Scophthalmidae', 'Scophthalmus', 458511, 145040, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Psetta maxima', 'Turbot', 'Rombo', 'Rodaballo', 'Scophthalmidae', 'Psetta', 458510, 145041, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Trachurus trachurus', 'Horse mackerel', 'Occhiotto', 'Jurel', 'Carangidae', 'Trachurus', 458519, 145042, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Caranx crysos', 'Blue runner', 'Carango', 'Jurel', 'Carangidae', 'Caranx', 458459, 145043, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sphyraena viridensis', 'Yellowmouth barracuda', 'Barracuda', 'Barracuda', 'Sphyraenidae', 'Sphyraena', 458516, 145044, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pomatomus saltatrix', 'Bluefish', 'Pesce serra', 'Anjova', 'Pomatomidae', 'Pomatomus', 458509, 145045, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Coryphaena hippurus', 'Common dolphinfish', 'Lampuga', 'Dorado', 'Coryphaenidae', 'Coryphaena', 458466, 145046, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Trisopterus luscus', 'Pouting', 'Trisoptero', 'Faneca', 'Gadidae', 'Trisopterus', 458520, 145047, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Micromesistius poutassou', 'Blue whiting', 'Merlano', 'Merluza', 'Gadidae', 'Micromesistius', 458495, 145048, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Phycis phycis', 'Forkbeard', 'Mostella', 'Mostela', 'Phycidae', 'Phycis', 458508, 145049, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Arnoglossus laterna', 'Scaldfish', 'Passera', 'Lenguado', 'Bothidae', 'Arnoglossus', 458451, 145050, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pegusa lascaris', 'Sand sole', 'Lingua', 'Lenguado', 'Soleidae', 'Pegusa', 458507, 145051, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Platichthys flesus', 'European flounder', 'Passera', 'Platija', 'Pleuronectidae', 'Platichthys', 458509, 145052, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Chelidonichthys lucerna', 'Tub gurnard', 'Capone', 'Rubio', 'Triglidae', 'Chelidonichthys', 458461, 145053, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Trigla lyra', 'Piper gurnard', 'Capone', 'Rubio', 'Triglidae', 'Trigla', 458520, 145054, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Dactylopterus volitans', 'Flying gurnard', 'Pesce volante', 'Pez volador', 'Dactylopteridae', 'Dactylopterus', 458467, 145055, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Callionymus lyra', 'Tub gurnard', 'Dragoncello', 'Pez arana', 'Callionymidae', 'Callionymus', 458457, 145056, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Capros aper', 'Boarfish', 'Capros', 'Chicharro', 'Caproidae', 'Capros', 458458, 145057, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Cepola macrophthalma', 'Red bandfish', 'Cepola', 'Pez cinta', 'Cepolidae', 'Cepola', 458460, 145058, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Atherina boyeri', 'Big-scale sand smelt', 'Alletta', 'Chinguillo', 'Atherinidae', 'Atherina', 458453, 145059, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sprattus sprattus', 'European sprat', 'Spratto', 'Espadin', 'Clupeidae', 'Sprattus', 458516, 145060, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Belone euxini', 'Black Sea garfish', 'Aguglia', 'Aguja', 'Belonidae', 'Belone', 458455, 145061, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Aulostomus strigosus', 'Atlantic trumpetfish', 'Pesce trombetta', 'Pez trompeta', 'Aulostomidae', 'Aulostomus', 458453, 145062, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Macroramphosus scolopax', 'Longspine snipefish', 'Pesce becco', 'Pez trompeta', 'Centriscidae', 'Macroramphosus', 458492, 145064, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Lagocephalus lagocephalus', 'Oceanic puffer', 'Pesce palla', 'Pez globo', 'Tetraodontidae', 'Lagocephalus', 458488, 145065, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Diodon holocanthus', 'Balloonfish', 'Pesce palla', 'Pez globo', 'Diodontidae', 'Diodon', 458468, 145066, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Monacanthus ciliatus', 'Fringed filefish', 'Pesce lima', 'Pez lima', 'Monacanthidae', 'Monacanthus', 458496, 145067, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Canthidermis maculata', 'Spotted triggerfish', 'Balestra maculata', 'Pez ballesta', 'Balistidae', 'Canthidermis', 458458, 145068, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pterois miles', 'Devil firefish', 'Pesce leone', 'Pez leon', 'Scorpaenidae', 'Pterois', 458511, 145069, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Scorpaena notata', 'Small scorpionfish', 'Scorfano piccolo', 'Rascacio', 'Scorpaenidae', 'Scorpaena', 458509, 145070, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Ophidion barbatum', 'Bearded cusk-eel', 'Ophidion', 'Ofidio', 'Ophidiidae', 'Ophidion', 458502, 145071, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Lepidopus caudatus', 'Silver scabbardfish', 'Pesce lama', 'Pez espada', 'Trichiuridae', 'Lepidopus', 458489, 145072, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Aphanopus carbo', 'Black scabbardfish', 'Pesce lama nero', 'Pez espada negro', 'Trichiuridae', 'Aphanopus', 458449, 145073, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Istiophorus albicans', 'Atlantic sailfish', 'Pesce vela', 'Pez vela', 'Istiophoridae', 'Istiophorus', 458481, 145074, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Makaira nigricans', 'Blue marlin', 'Marlin', 'Marlin azul', 'Istiophoridae', 'Makaira', 458492, 145075, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Lamna nasus', 'Porbeagle', 'Squalo mako', 'Marrajo', 'Lamnidae', 'Lamna', 458488, 145076, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Isurus oxyrinchus', 'Shortfin mako', 'Squalo mako', 'Mako', 'Lamnidae', 'Isurus', 458481, 145077, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Cetorhinus maximus', 'Basking shark', 'Squalo elefante', 'Tiburon peregrino', 'Cetorhinidae', 'Cetorhinus', 458461, 145078, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Hexanchus griseus', 'Bluntnose sixgill shark', 'Squalo grigio', 'Tiburon', 'Hexanchidae', 'Hexanchus', 458477, 145079, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Etmopterus spinax', 'Velvet belly lanternshark', 'Squalo velluto', 'Tiburon', 'Etmopteridae', 'Etmopterus', 458471, 145080, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Gymnura altavela', 'Spiny butterfly ray', 'Pastinaca', 'Raya mariposa', 'Gymnuridae', 'Gymnura', 458479, 145081, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Dasyatis pastinaca', 'Common stingray', 'Pastinaca', 'Raya latigo', 'Dasyatidae', 'Dasyatis', 458467, 145082, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Torpedo torpedo', 'Common torpedo', 'Triglia di mare', 'Raya electrica', 'Torpedinidae', 'Torpedo', 458519, 145083, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Rhinobatos rhinobatos', 'Common guitarfish', 'Razza chitarra', 'Pez guitarra', 'Rhinobatidae', 'Rhinobatos', 458510, 145084, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Mobula hypostoma', 'Atlantic devil ray', 'Manta', 'Manta', 'Mobulidae', 'Mobula', 458495, 145085, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pteroplatytrygon violacea', 'Pelagic stingray', 'Pastinaca', 'Raya latigo', 'Dasyatidae', 'Pteroplatytrygon', 458511, 145086, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Stenella coeruleoalba', 'Striped dolphin', 'Stenella', 'Delfin listado', 'Delphinidae', 'Stenella', 458516, 145087, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Delphinus delphis', 'Common dolphin', 'Delfino comune', 'Delfin comun', 'Delphinidae', 'Delphinus', 458467, 145088, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Grampus griseus', 'Risso dolphin', 'Grampo', 'Delfin de Risso', 'Delphinidae', 'Grampus', 458475, 145089, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Physeter macrocephalus', 'Sperm whale', 'Capodoglio', 'Cachalote', 'Physeteridae', 'Physeter', 458508, 145090, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Balaenoptera physalus', 'Fin whale', 'Balenottera comune', 'Rorcual comun', 'Balaenopteridae', 'Balaenoptera', 458454, 145091, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Lithognathus lithognathus', 'White steenbras', 'Mormora', 'Mormora', 'Sparidae', 'Lithognathus', 458491, 145092, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Pagellus acarne', 'Axillary seabream', 'Pagello', 'Pargo', 'Sparidae', 'Pagellus', 458505, 145093, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus annularis', 'Annular seabream', 'Sarago sparro', 'Sargo', 'Sparidae', 'Diplodus', 458468, 145094, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus puntazzo', 'Sharpsnout seabream', 'Sarago pizzuto', 'Sargo', 'Sparidae', 'Diplodus', 458469, 145095, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus cervinus', 'White seabream', 'Sarago cervino', 'Sargo', 'Sparidae', 'Diplodus', 458468, 145096, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Spicara smaris', 'Picarel', 'Spicarelo', 'Mendole', 'Sparidae', 'Spicara', 458515, 145097, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Spicara maena', 'Blotched picarel', 'Spicarelo', 'Mendole', 'Sparidae', 'Spicara', 458515, 145098, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Centracanthus cirrus', 'Picarel', 'Centolabro', 'Mendole', 'Centracanthidae', 'Centracanthus', 458461, 145099, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Acanthodoris pilosa', 'Hairy dorid', 'Nudibranch', 'Nudibranquio', 'Onchidorididae', 'Acanthodoris', 458448, 145100, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Berghia coerulescens', 'Blue nudibranch', 'Nudibranch', 'Nudibranquio', 'Aeolidiidae', 'Berghia', 458455, 145101, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Tethys fimbria', 'Melon sea slug', 'Nudibranch', 'Nudibranquio', 'Tethydidae', 'Tethys', 458518, 145102, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Aplysia depilans', 'Depilating sea hare', 'Lepre di mare', 'Liebre de mar', 'Aplysiidae', 'Aplysia', 458447, 145103, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Janthina janthina', 'Violet sea-snail', 'Giannetta', 'Caracol violeta', 'Janthinidae', 'Janthina', 458483, 145104, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Physalia physalis', 'Portuguese man o war', 'Caravella', 'Carabela portuguesa', 'Physaliidae', 'Physalia', 458508, 145105, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Chrysaora hysoscella', 'Compass jellyfish', 'Medusa bussola', 'Medusa brujula', 'Pelagiidae', 'Chrysaora', 458463, 145106, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Mnemiopsis leidyi', 'Sea walnut', 'Ctenoforo', 'Ctenoforo', 'Bolinopsidae', 'Mnemiopsis', 458496, 145107, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Beroe ovata', 'Ovate comb jelly', 'Ctenoforo', 'Ctenoforo', 'Beroidae', 'Beroe', 458455, 145108, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Sargassum vulgare', 'Common gulfweed', 'Sargasso', 'Sargazo', 'Sargassaceae', 'Sargassum', 458511, 145109, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Caulerpa prolifera', 'Green algae', 'Caulerpa', 'Caulerpa', 'Caulerpaceae', 'Caulerpa', 458459, 145110, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Padina pavonica', 'Peacock tail algae', 'Padina', 'Padina', 'Dictyotaceae', 'Padina', 458505, 145111, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Lithophyllum incrustans', 'Encrusting algae', 'Lithophyllum', 'Lithophyllum', 'Corallinaceae', 'Lithophyllum', 458490, 145112, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Acetabularia acetabulum', 'Mermaid wineglass', 'Acetabularia', 'Acetabularia', 'Polyphysaceae', 'Acetabularia', 458448, 145113, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Halimeda tuna', 'Green calcareous algae', 'Halimeda', 'Halimeda', 'Halimedaceae', 'Halimeda', 458476, 145114, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Cystoseira compressa', 'Brown seaweed', 'Cystoseira', 'Cystoseira', 'Sargassaceae', 'Cystoseira', 458467, 145115, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Ulva lactuca', 'Sea lettuce', 'Lattuga di mare', 'Lechuga de mar', 'Ulvaceae', 'Ulva', 458521, 145116, 273749, 'Animalia', '{"seed": true}'::jsonb),
  ('Gracilaria gracilis', 'Red algae', 'Gracilaria', 'Gracilaria', 'Gracilariaceae', 'Gracilaria', 458475, 145117, 273749, 'Animalia', '{"seed": true}'::jsonb)
ON CONFLICT (scientific_name) DO UPDATE SET
  common_name = EXCLUDED.common_name,
  common_name_it = EXCLUDED.common_name_it,
  common_name_es = EXCLUDED.common_name_es,
  inat_taxon_id = EXCLUDED.inat_taxon_id,
  worms_id = EXCLUDED.worms_id,
  gbif_taxon_key = EXCLUDED.gbif_taxon_key,
  updated_at = now();

INSERT INTO operators (name, slug, country_code, operator_type, location, address, email, phone, website, subscription_tier, subscription_status, metadata)
VALUES
  ('Diving Center Ustica', 'diving-center-ustica', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(13.185, 38.705), 4326)::geography, 'Via Cristoforo Colombo 12, Ustica', 'info@divingustica.it', '+39 091 844 9001', 'https://divingustica.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Portofino Divers', 'portofino-divers', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(9.2095, 44.3035), 4326)::geography, 'Via Fondaco 5, Portofino', 'info@portofinodivers.it', '+39 0185 269 012', 'https://portofinodivers.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Elba Sub', 'elba-sub', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(10.321, 42.8145), 4326)::geography, 'Via del Molo 3, Portoferraio', 'info@elbasub.it', '+39 0565 918 234', 'https://elbasub.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Sardinia Dive Experience', 'sardinia-dive-experience', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(9.518, 39.102), 4326)::geography, 'Via Molo Umberto I, Villasimius', 'info@sardiniadive.it', '+39 070 792 456', 'https://sardiniadive.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Scuba Academy Siracusa', 'scuba-academy-siracusa', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(15.29, 37.075), 4326)::geography, 'Lungomare Alfeo 22, Siracusa', 'info@scubaacademy.it', '+39 0931 462 88', 'https://scubaacademy.it', 'starter', 'active', '{"seed": true}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  updated_at = now();

INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'diving-center-ustica' AND ds.slug = 'ustica-secca-colobbara'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'portofino-divers' AND ds.slug = 'ustica-punta-gavazzi'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'elba-sub' AND ds.slug = 'ustica-grotta-gamberi'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'sardinia-dive-experience' AND ds.slug = 'portofino-cristo-abissi'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'scuba-academy-siracusa' AND ds.slug = 'portofino-punta-faro'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;

INSERT INTO badges (code, name, description, criteria_type, criteria_value, tier)
VALUES
  ('first-dive', 'First Splash', 'Log your first dive in Benthyo', 'dive_count', '{"count":1}'::jsonb, 1),
  ('ten-dives', 'Deco Disciple', 'Complete 10 logged dives', 'dive_count', '{"count":10}'::jsonb, 1),
  ('fifty-dives', 'Reef Regular', 'Complete 50 logged dives', 'dive_count', '{"count":50}'::jsonb, 2),
  ('hundred-dives', 'Centurion Diver', 'Complete 100 logged dives', 'dive_count', '{"count":100}'::jsonb, 3),
  ('first-species', 'Species Spotter', 'Record your first species sighting', 'species_count', '{"count":1}'::jsonb, 1),
  ('twenty-species', 'Life List Builder', 'See 20 different species', 'species_count', '{"count":20}'::jsonb, 2),
  ('fifty-species', 'Marine Naturalist', 'See 50 different species', 'species_count', '{"count":50}'::jsonb, 3),
  ('five-sites', 'Site Explorer', 'Dive at 5 different sites', 'site_count', '{"count":5}'::jsonb, 1),
  ('med-explorer', 'Mediterranean Explorer', 'Log a dive in the Mediterranean region', 'region', '{"regions":["mediterranean"]}'::jsonb, 2),
  ('group-grouper', 'Grouper Guardian', 'Spot a dusky grouper (Epinephelus marginatus)', 'manual', '{"species":"Epinephelus marginatus"}'::jsonb, 3)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  criteria_type = EXCLUDED.criteria_type,
  criteria_value = EXCLUDED.criteria_value,
  tier = EXCLUDED.tier;

COMMIT;
