-- Benthyo seed data (idempotent)
-- 50 Mediterranean dive sites, 200 marine species, 5 Italian operators, 10 badges

BEGIN;

INSERT INTO dive_sites (name, slug, description, location, country_code, region, depth_min, depth_max, difficulty, site_type, access_type, verified, metadata)
VALUES
  ('Ustica Secca della Colobbara', 'ustica-secca-colobbara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.18, 38.71), 4326)::geography, 'IT', 'Sicily', 5, 45, 'advanced', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ustica Secca di Punta Gavazzi', 'ustica-punta-gavazzi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.175, 38.695), 4326)::geography, 'IT', 'Sicily', 8, 50, 'advanced', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ustica Grotta dei Gamberi', 'ustica-grotta-gamberi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.19, 38.7), 4326)::geography, 'IT', 'Sicily', 10, 35, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Portofino Christ of the Abyss', 'portofino-cristo-abissi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.2167, 44.3167), 4326)::geography, 'IT', 'Liguria', 12, 18, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Portofino Punta del Faro', 'portofino-punta-faro', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.21, 44.303), 4326)::geography, 'IT', 'Liguria', 15, 40, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Elba Pomonte Wreck', 'elba-pomonte-wreck', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(10.12, 42.745), 4326)::geography, 'IT', 'Tuscany', 12, 18, 'beginner', 'wreck', 'shore', true, '{"seed": true}'::jsonb),
  ('Elba Scoglietto di Portoferraio', 'elba-scoglietto', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(10.32, 42.815), 4326)::geography, 'IT', 'Tuscany', 5, 25, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Sardinia Tavolara Punta Timi', 'sardinia-tavolara-timi', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.72, 40.91), 4326)::geography, 'IT', 'Sardinia', 10, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Sardinia Capo Carbonara', 'sardinia-capo-carbonara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.52, 39.1), 4326)::geography, 'IT', 'Sardinia', 5, 30, 'beginner', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Sardinia Nora Roman Ruins', 'sardinia-nora-ruins', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(9.01, 39), 4326)::geography, 'IT', 'Sardinia', 3, 12, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Lampedusa Secchitello', 'lampedusa-secchitello', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(12.61, 35.52), 4326)::geography, 'IT', 'Pelagie Islands', 15, 50, 'advanced', 'pinnacle', 'boat', true, '{"seed": true}'::jsonb),
  ('Lampedusa Tabaccara', 'lampedusa-tabaccara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(12.6, 35.5), 4326)::geography, 'IT', 'Pelagie Islands', 5, 20, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Pantelleria Grotta di Sataria', 'pantelleria-sataria', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(11.95, 36.83), 4326)::geography, 'IT', 'Sicily', 5, 15, 'beginner', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Ischia Secca delle Formiche', 'ischia-formiche', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.95, 40.73), 4326)::geography, 'IT', 'Campania', 10, 40, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Procida Vivara Island', 'procida-vivara', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.02, 40.76), 4326)::geography, 'IT', 'Campania', 5, 25, 'beginner', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ponza Secca di Frontone', 'ponza-frontone', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(12.96, 40.91), 4326)::geography, 'IT', 'Lazio', 8, 35, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Ventotene Secca di Santo Stefano', 'ventotene-santo-stefano', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(13.43, 40.8), 4326)::geography, 'IT', 'Lazio', 10, 45, 'advanced', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Capri Blue Grotto Area', 'capri-blue-grotto', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.21, 40.56), 4326)::geography, 'IT', 'Campania', 5, 30, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Sorrento Bagni della Regina', 'sorrento-bagni-regina', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.38, 40.63), 4326)::geography, 'IT', 'Campania', 5, 20, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Amalfi Li Galli', 'amalfi-li-galli', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.25, 40.55), 4326)::geography, 'IT', 'Campania', 15, 40, 'advanced', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Cilento Punta Licosa', 'cilento-licosa', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.9, 40.25), 4326)::geography, 'IT', 'Campania', 8, 30, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Tremiti San Domino', 'tremiti-san-domino', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(15.5, 42.12), 4326)::geography, 'IT', 'Puglia', 5, 35, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Otranto Punta Palascia', 'otranto-palascia', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(18.51, 40.13), 4326)::geography, 'IT', 'Puglia', 5, 25, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Gallipoli Molo di San Andrea', 'gallipoli-san-andrea', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(17.99, 40.05), 4326)::geography, 'IT', 'Puglia', 3, 15, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Cirkewwa Reef', 'malta-cirkewwa', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.33, 35.99), 4326)::geography, 'MT', 'Malta', 5, 30, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Um El Faroud Wreck', 'malta-um-el-faroud', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.54, 35.82), 4326)::geography, 'MT', 'Malta', 18, 35, 'intermediate', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('Malta Blue Hole Gozo', 'malta-blue-hole-gozo', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.19, 36.055), 4326)::geography, 'MT', 'Gozo', 5, 40, 'intermediate', 'wall', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Inland Sea', 'malta-inland-sea', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.185, 36.052), 4326)::geography, 'MT', 'Gozo', 5, 25, 'intermediate', 'wall', 'shore', true, '{"seed": true}'::jsonb),
  ('Malta Reqqa Point', 'malta-reqqa-point', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.23, 36.08), 4326)::geography, 'MT', 'Gozo', 10, 45, 'advanced', 'wall', 'shore', true, '{"seed": true}'::jsonb),
  ('Croatia Vis Blue Cave', 'croatia-vis-blue-cave', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(16.04, 43.05), 4326)::geography, 'HR', 'Vis', 5, 20, 'beginner', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Bisevo Blue Cave', 'croatia-bisevo-blue-cave', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(16.04, 42.98), 4326)::geography, 'HR', 'Vis', 5, 15, 'beginner', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Taranto Wreck', 'croatia-taranto-wreck', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(16.44, 43.17), 4326)::geography, 'HR', 'Hvar', 20, 42, 'advanced', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Premuda Cathedral', 'croatia-premuda-cathedral', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(14.6, 44.33), 4326)::geography, 'HR', 'Premuda', 15, 50, 'advanced', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Croatia Kornati Mana', 'croatia-kornati-mana', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(15.35, 43.79), 4326)::geography, 'HR', 'Kornati', 5, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Zakynthos Keri Caves', 'greece-zakynthos-keri', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(20.82, 37.68), 4326)::geography, 'GR', 'Ionian Islands', 5, 25, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Mykonos Paradise Reef', 'greece-mykonos-paradise', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(25.35, 37.42), 4326)::geography, 'GR', 'Cyclades', 5, 30, 'beginner', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Santorini Nea Kameni', 'greece-santorini-nea-kameni', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(25.4, 36.4), 4326)::geography, 'GR', 'Cyclades', 10, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Crete Elephant Cave', 'greece-crete-elephant-cave', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(24.25, 35.42), 4326)::geography, 'GR', 'Crete', 8, 20, 'intermediate', 'cave', 'boat', true, '{"seed": true}'::jsonb),
  ('Greece Rhodes Anthony Quinn Bay', 'greece-rhodes-anthony-quinn', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(28.23, 36.44), 4326)::geography, 'GR', 'Dodecanese', 5, 25, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Spain Medes Islands Tasco Petit', 'spain-medes-tasco-petit', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(3.22, 42.05), 4326)::geography, 'ES', 'Catalonia', 10, 35, 'intermediate', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Spain Cabo de Palos Isla Hormiga', 'spain-cabo-palos-hormiga', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(-0.68, 37.63), 4326)::geography, 'ES', 'Murcia', 10, 45, 'advanced', 'reef', 'boat', true, '{"seed": true}'::jsonb),
  ('Spain Cabo de Gata La Foradada', 'spain-cabo-gata-foradada', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(-2.19, 36.72), 4326)::geography, 'ES', 'Andalusia', 5, 20, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Spain Ibiza Don Pedro Wreck', 'spain-ibiza-don-pedro', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(1.42, 38.88), 4326)::geography, 'ES', 'Balearic Islands', 25, 45, 'advanced', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('France Port-Cros La Gabinière', 'france-port-cros-gabiniere', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(6.39, 43.01), 4326)::geography, 'FR', 'Var', 10, 40, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('France Cerbère Banyuls Reserve', 'france-cerbere-banyuls', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(3.16, 42.44), 4326)::geography, 'FR', 'Occitanie', 5, 30, 'intermediate', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('France Marseille Les Catalans', 'france-marseille-catalans', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(5.36, 43.29), 4326)::geography, 'FR', 'Provence', 5, 25, 'beginner', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('France Nice Cap Ferrat', 'france-nice-cap-ferrat', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(7.33, 43.69), 4326)::geography, 'FR', 'Alpes-Maritimes', 10, 35, 'intermediate', 'wall', 'boat', true, '{"seed": true}'::jsonb),
  ('Monaco Larvotto Reserve', 'monaco-larvotto', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(7.43, 43.75), 4326)::geography, 'MC', 'Monaco', 8, 30, 'intermediate', 'reef', 'shore', true, '{"seed": true}'::jsonb),
  ('Cyprus Zenobia Wreck', 'cyprus-zenobia', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(33.65, 34.89), 4326)::geography, 'CY', 'Larnaca', 16, 42, 'advanced', 'wreck', 'boat', true, '{"seed": true}'::jsonb),
  ('Egypt Ras Mohammed Shark Reef', 'egypt-ras-mohammed', 'Popular Mediterranean dive site.', ST_SetSRID(ST_MakePoint(34.25, 27.73), 4326)::geography, 'EG', 'Sinai', 5, 40, 'advanced', 'wall', 'boat', true, '{"seed": true}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  location = EXCLUDED.location,
  depth_min = EXCLUDED.depth_min,
  depth_max = EXCLUDED.depth_max,
  updated_at = now();

-- NOTE: external taxon IDs (inat_taxon_id / worms_id / gbif_taxon_key) are
-- intentionally NOT seeded here. The previous hardcoded values were fabricated
-- (duplicated / sequential placeholders) and broke photo enrichment. They are
-- now resolved from live APIs by the ETL steps (species-seed, worms,
-- inat-taxon-lookup). This seed only provides curated names, which the ETL
-- never overwrites (see COALESCE below).
INSERT INTO species (scientific_name, common_name, common_name_it, common_name_es, family, genus, kingdom, metadata)
VALUES
  ('Epinephelus marginatus', 'Dusky grouper', 'Cernia bruna', 'Mero', 'Serranidae', 'Epinephelus', 'Animalia', '{"seed": true}'::jsonb),
  ('Thalassoma pavo', 'Ornate wrasse', 'Tordo pavone', 'Pez verde', 'Labridae', 'Thalassoma', 'Animalia', '{"seed": true}'::jsonb),
  ('Sparisoma cretense', 'Parrotfish', 'Pesce pappagallo', 'Pez loro', 'Scaridae', 'Sparisoma', 'Animalia', '{"seed": true}'::jsonb),
  ('Coris julis', 'Mediterranean rainbow wrasse', 'Tordo', 'Doncella', 'Labridae', 'Coris', 'Animalia', '{"seed": true}'::jsonb),
  ('Chromis chromis', 'Damselfish', 'Castagnola', 'Castañuela', 'Pomacentridae', 'Chromis', 'Animalia', '{"seed": true}'::jsonb),
  ('Anthias anthias', 'Swallowtail seaperch', 'Anthias', 'Breca', 'Serranidae', 'Anthias', 'Animalia', '{"seed": true}'::jsonb),
  ('Sciaena umbra', 'Brown meagre', 'Corvina', 'Corvina', 'Sciaenidae', 'Sciaena', 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus sargus', 'White seabream', 'Sarago maggiore', 'Sargo', 'Sparidae', 'Diplodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus vulgaris', 'Two-banded seabream', 'Sarago comune', 'Sargo común', 'Sparidae', 'Diplodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Sarpa salpa', 'Salema', 'Salpa', 'Salpa', 'Sparidae', 'Sarpa', 'Animalia', '{"seed": true}'::jsonb),
  ('Boops boops', 'Bogue', 'Tanuta', 'Boga', 'Sparidae', 'Boops', 'Animalia', '{"seed": true}'::jsonb),
  ('Oblada melanura', 'Saddled seabream', 'Oblada', 'Chopa', 'Sparidae', 'Oblada', 'Animalia', '{"seed": true}'::jsonb),
  ('Pagellus erythrinus', 'Common pandora', 'Pagello', 'Pargo', 'Sparidae', 'Pagellus', 'Animalia', '{"seed": true}'::jsonb),
  ('Lithognathus mormyrus', 'Striped seabream', 'Mormora', 'Mormora', 'Sparidae', 'Lithognathus', 'Animalia', '{"seed": true}'::jsonb),
  ('Symphodus tinca', 'Peacock wrasse', 'Tordo verde', 'Doncella', 'Labridae', 'Symphodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Labrus merula', 'Brown wrasse', 'Tordo nero', 'Doncella', 'Labridae', 'Labrus', 'Animalia', '{"seed": true}'::jsonb),
  ('Xyrichtys novacula', 'Pearly razorfish', 'Pesce luna', 'Pez ballesta', 'Labridae', 'Xyrichtys', 'Animalia', '{"seed": true}'::jsonb),
  ('Centrolabrus trutta', 'Small-mouth wrasse', 'Tordo piccolo', 'Doncella', 'Labridae', 'Centrolabrus', 'Animalia', '{"seed": true}'::jsonb),
  ('Mullus surmuletus', 'Striped red mullet', 'Triglia di fango', 'Salmonete', 'Mullidae', 'Mullus', 'Animalia', '{"seed": true}'::jsonb),
  ('Mullus barbatus', 'Red mullet', 'Triglia', 'Salmonete', 'Mullidae', 'Mullus', 'Animalia', '{"seed": true}'::jsonb),
  ('Trachinus draco', 'Greater weever', 'Pesce scorpione', 'Pez araña', 'Trachinidae', 'Trachinus', 'Animalia', '{"seed": true}'::jsonb),
  ('Uranoscopus scaber', 'Stargazer', 'Ragno di mare', 'Pez rata', 'Uranoscopidae', 'Uranoscopus', 'Animalia', '{"seed": true}'::jsonb),
  ('Scomber scombrus', 'Atlantic mackerel', 'Sgombro', 'Caballa', 'Scombridae', 'Scomber', 'Animalia', '{"seed": true}'::jsonb),
  ('Sarda sarda', 'Atlantic bonito', 'Palamita', 'Bonito', 'Scombridae', 'Sarda', 'Animalia', '{"seed": true}'::jsonb),
  ('Thunnus thynnus', 'Bluefin tuna', 'Tonno rosso', 'Atún rojo', 'Scombridae', 'Thunnus', 'Animalia', '{"seed": true}'::jsonb),
  ('Belone belone', 'Garfish', 'Aguglia', 'Aguja', 'Belonidae', 'Belone', 'Animalia', '{"seed": true}'::jsonb),
  ('Fistularia commersonii', 'Red cornetfish', 'Fistularia', 'Pez pipa', 'Fistulariidae', 'Fistularia', 'Animalia', '{"seed": true}'::jsonb),
  ('Syngnathus abaster', 'Pipefish', 'Pesce ago', 'Pez pipa', 'Syngnathidae', 'Syngnathus', 'Animalia', '{"seed": true}'::jsonb),
  ('Hippocampus hippocampus', 'Short-snouted seahorse', 'Cavalluccio marino', 'Caballito de mar', 'Syngnathidae', 'Hippocampus', 'Animalia', '{"seed": true}'::jsonb),
  ('Octopus vulgaris', 'Common octopus', 'Polpo', 'Pulpo', 'Octopodidae', 'Octopus', 'Animalia', '{"seed": true}'::jsonb),
  ('Sepia officinalis', 'Common cuttlefish', 'Seppia', 'Sepia', 'Sepiidae', 'Sepia', 'Animalia', '{"seed": true}'::jsonb),
  ('Sepiola atlantica', 'Little cuttlefish', 'Sepiola', 'Sepiola', 'Sepiolidae', 'Sepiola', 'Animalia', '{"seed": true}'::jsonb),
  ('Loligo vulgaris', 'European squid', 'Calamaro', 'Calamar', 'Loliginidae', 'Loligo', 'Animalia', '{"seed": true}'::jsonb),
  ('Eledone moschata', 'Musky octopus', 'Polpo muschiato', 'Pulpo almizclero', 'Octopodidae', 'Eledone', 'Animalia', '{"seed": true}'::jsonb),
  ('Palinurus elephas', 'Spiny lobster', 'Aragosta', 'Langosta', 'Palinuridae', 'Palinurus', 'Animalia', '{"seed": true}'::jsonb),
  ('Homarus gammarus', 'European lobster', 'Astice', 'Bogavante', 'Nephropidae', 'Homarus', 'Animalia', '{"seed": true}'::jsonb),
  ('Scyllarides latus', 'Slipper lobster', 'Cicale di mare', 'Cigarra de mar', 'Scyllaridae', 'Scyllarides', 'Animalia', '{"seed": true}'::jsonb),
  ('Maja squinado', 'Spider crab', 'Granchio ragno', 'Centollo', 'Majidae', 'Maja', 'Animalia', '{"seed": true}'::jsonb),
  ('Pachygrapsus marmoratus', 'Marbled rock crab', 'Granchio di scoglio', 'Cangrejo', 'Grapsidae', 'Pachygrapsus', 'Animalia', '{"seed": true}'::jsonb),
  ('Carcinus maenas', 'Green crab', 'Granchio verde', 'Cangrejo verde', 'Carcinidae', 'Carcinus', 'Animalia', '{"seed": true}'::jsonb),
  ('Paracentrotus lividus', 'Purple sea urchin', 'Riccio di mare', 'Erizo de mar', 'Parechinidae', 'Paracentrotus', 'Animalia', '{"seed": true}'::jsonb),
  ('Arbacia lixula', 'Black sea urchin', 'Riccio nero', 'Erizo negro', 'Arbaciidae', 'Arbacia', 'Animalia', '{"seed": true}'::jsonb),
  ('Astroides calycularis', 'Orange coral', 'Astroides', 'Coral naranja', 'Dendrophylliidae', 'Astroides', 'Animalia', '{"seed": true}'::jsonb),
  ('Paramuricea clavata', 'Red gorgonian', 'Gorgonia rossa', 'Gorgonia roja', 'Paramuriceidae', 'Paramuricea', 'Animalia', '{"seed": true}'::jsonb),
  ('Eunicella singularis', 'White gorgonian', 'Gorgonia bianca', 'Gorgonia blanca', 'Gorgoniidae', 'Eunicella', 'Animalia', '{"seed": true}'::jsonb),
  ('Antipathella subpinnata', 'Yellow black coral', 'Corallo nero', 'Coral negro', 'Myriopathidae', 'Antipathella', 'Animalia', '{"seed": true}'::jsonb),
  ('Cladocora caespitosa', 'Mediterranean pillow coral', 'Madrepora a cuscino', 'Coral cojín', 'Cladocoridae', 'Cladocora', 'Animalia', '{"seed": true}'::jsonb),
  ('Corynactis viridis', 'Strawberry anemone', 'Anemone fragola', 'Anémona fresa', 'Corallimorphidae', 'Corynactis', 'Animalia', '{"seed": true}'::jsonb),
  ('Anemonia viridis', 'Snakelocks anemone', 'Anemone di mare', 'Anémona de mar', 'Actiniidae', 'Anemonia', 'Animalia', '{"seed": true}'::jsonb),
  ('Actinia equina', 'Beadlet anemone', 'Anemone rossa', 'Anémona roja', 'Actiniidae', 'Actinia', 'Animalia', '{"seed": true}'::jsonb),
  ('Cerianthus membranaceus', 'Tube anemone', 'Ceriantho', 'Ceriantho', 'Cerianthidae', 'Cerianthus', 'Animalia', '{"seed": true}'::jsonb),
  ('Scorpaena scrofa', 'Red scorpionfish', 'Scorfano rosso', 'Rascacio', 'Scorpaenidae', 'Scorpaena', 'Animalia', '{"seed": true}'::jsonb),
  ('Scorpaena porcus', 'Black scorpionfish', 'Scorfano nero', 'Rascacio', 'Scorpaenidae', 'Scorpaena', 'Animalia', '{"seed": true}'::jsonb),
  ('Apogon imberbis', 'Cardinalfish', 'Cardinale', 'Cardinal', 'Apogonidae', 'Apogon', 'Animalia', '{"seed": true}'::jsonb),
  ('Conger conger', 'European conger', 'Grongo', 'Congrio', 'Congridae', 'Conger', 'Animalia', '{"seed": true}'::jsonb),
  ('Muraena helena', 'Mediterranean moray', 'Murena', 'Morena', 'Muraenidae', 'Muraena', 'Animalia', '{"seed": true}'::jsonb),
  ('Gymnothorax unicolor', 'Mediterranean moray', 'Murena', 'Morena', 'Muraenidae', 'Gymnothorax', 'Animalia', '{"seed": true}'::jsonb),
  ('Serranus cabrilla', 'Comber', 'Perchia', 'Serrano', 'Serranidae', 'Serranus', 'Animalia', '{"seed": true}'::jsonb),
  ('Serranus scriba', 'Painted comber', 'Perchia', 'Serrano', 'Serranidae', 'Serranus', 'Animalia', '{"seed": true}'::jsonb),
  ('Epinephelus costae', 'Goldblotch grouper', 'Cernia maculata', 'Mero', 'Serranidae', 'Epinephelus', 'Animalia', '{"seed": true}'::jsonb),
  ('Mycteroperca rubra', 'Mottled grouper', 'Cernia rossa', 'Mero', 'Serranidae', 'Mycteroperca', 'Animalia', '{"seed": true}'::jsonb),
  ('Balistes capriscus', 'Grey triggerfish', 'Balestra', 'Pez ballesta', 'Balistidae', 'Balistes', 'Animalia', '{"seed": true}'::jsonb),
  ('Dentex dentex', 'Common dentex', 'Dentice', 'Denton', 'Sparidae', 'Dentex', 'Animalia', '{"seed": true}'::jsonb),
  ('Pagrus pagrus', 'Red porgy', 'Pagro', 'Pagre', 'Sparidae', 'Pagrus', 'Animalia', '{"seed": true}'::jsonb),
  ('Seriola dumerili', 'Greater amberjack', 'Ricciola', 'Serviola', 'Carangidae', 'Seriola', 'Animalia', '{"seed": true}'::jsonb),
  ('Sphyraena sphyraena', 'European barracuda', 'Barracuda', 'Barracuda', 'Sphyraenidae', 'Sphyraena', 'Animalia', '{"seed": true}'::jsonb),
  ('Zeus faber', 'John Dory', 'Pesce San Pietro', 'Pez de San Pedro', 'Zeidae', 'Zeus', 'Animalia', '{"seed": true}'::jsonb),
  ('Xiphias gladius', 'Swordfish', 'Pesce spada', 'Pez espada', 'Xiphiidae', 'Xiphias', 'Animalia', '{"seed": true}'::jsonb),
  ('Merluccius merluccius', 'European hake', 'Nasello', 'Merluza', 'Merlucciidae', 'Merluccius', 'Animalia', '{"seed": true}'::jsonb),
  ('Engraulis encrasicolus', 'European anchovy', 'Acciuga', 'Anchoa', 'Engraulidae', 'Engraulis', 'Animalia', '{"seed": true}'::jsonb),
  ('Sardina pilchardus', 'Sardine', 'Sardina', 'Sardina', 'Clupeidae', 'Sardina', 'Animalia', '{"seed": true}'::jsonb),
  ('Chelonia mydas', 'Green sea turtle', 'Tartaruga verde', 'Tortuga verde', 'Cheloniidae', 'Chelonia', 'Animalia', '{"seed": true}'::jsonb),
  ('Caretta caretta', 'Loggerhead sea turtle', 'Tartaruga caretta', 'Tortuga boba', 'Cheloniidae', 'Caretta', 'Animalia', '{"seed": true}'::jsonb),
  ('Tursiops truncatus', 'Bottlenose dolphin', 'Tursiope', 'Delfin mular', 'Delphinidae', 'Tursiops', 'Animalia', '{"seed": true}'::jsonb),
  ('Monachus monachus', 'Mediterranean monk seal', 'Foca monaca', 'Foca monje', 'Phocidae', 'Monachus', 'Animalia', '{"seed": true}'::jsonb),
  ('Torpedo marmorata', 'Marbled electric ray', 'Triglia di mare', 'Raya electrica', 'Torpedinidae', 'Torpedo', 'Animalia', '{"seed": true}'::jsonb),
  ('Raja clavata', 'Thornback ray', 'Razza chiodata', 'Raya', 'Rajidae', 'Raja', 'Animalia', '{"seed": true}'::jsonb),
  ('Myliobatis aquila', 'Common eagle ray', 'Pastinaca aquila', 'Aguila marmorea', 'Myliobatidae', 'Myliobatis', 'Animalia', '{"seed": true}'::jsonb),
  ('Squatina squatina', 'Angelshark', 'Squalo angelo', 'Tiburon angel', 'Squatinidae', 'Squatina', 'Animalia', '{"seed": true}'::jsonb),
  ('Galeus melastomus', 'Blackmouth catshark', 'Gattuccio', 'Gato marino', 'Scyliorhinidae', 'Galeus', 'Animalia', '{"seed": true}'::jsonb),
  ('Scyliorhinus stellaris', 'Nursehound', 'Gattuccio maculato', 'Gato marino', 'Scyliorhinidae', 'Scyliorhinus', 'Animalia', '{"seed": true}'::jsonb),
  ('Mustelus mustelus', 'Smooth-hound', 'Verdesca', 'Tiburon', 'Triakidae', 'Mustelus', 'Animalia', '{"seed": true}'::jsonb),
  ('Mobula mobular', 'Giant devil ray', 'Manta', 'Manta', 'Mobulidae', 'Mobula', 'Animalia', '{"seed": true}'::jsonb),
  ('Posidonia oceanica', 'Neptune grass', 'Posidonia', 'Posidonia', 'Posidoniaceae', 'Posidonia', 'Animalia', '{"seed": true}'::jsonb),
  ('Cymodocea nodosa', 'Little Neptune grass', 'Cymodocea', 'Cymodocea', 'Cymodoceaceae', 'Cymodocea', 'Animalia', '{"seed": true}'::jsonb),
  ('Caulerpa taxifolia', 'Killer algae', 'Caulerpa', 'Caulerpa', 'Caulerpaceae', 'Caulerpa', 'Animalia', '{"seed": true}'::jsonb),
  ('Corallina officinalis', 'Coral weed', 'Corallina', 'Corallina', 'Corallinaceae', 'Corallina', 'Animalia', '{"seed": true}'::jsonb),
  ('Pelagia noctiluca', 'Mauve stinger', 'Pelagia', 'Medusa', 'Pelagiidae', 'Pelagia', 'Animalia', '{"seed": true}'::jsonb),
  ('Aurelia aurita', 'Moon jellyfish', 'Medusa lunare', 'Medusa lunar', 'Ulmaridae', 'Aurelia', 'Animalia', '{"seed": true}'::jsonb),
  ('Rhizostoma pulmo', 'Barrel jellyfish', 'Medusa', 'Medusa', 'Rhizostomatidae', 'Rhizostoma', 'Animalia', '{"seed": true}'::jsonb),
  ('Cotylorhiza tuberculata', 'Fried egg jellyfish', 'Medusa uovo', 'Medusa huevo frito', 'Cepheidae', 'Cotylorhiza', 'Animalia', '{"seed": true}'::jsonb),
  ('Flabellina affinis', 'Purple nudibranch', 'Nudibranch', 'Nudibranquio', 'Flabellinidae', 'Flabellina', 'Animalia', '{"seed": true}'::jsonb),
  ('Felimare picta', 'Painted nudibranch', 'Nudibranch', 'Nudibranquio', 'Chromodorididae', 'Felimare', 'Animalia', '{"seed": true}'::jsonb),
  ('Cratena peregrina', 'Peregrine aeolid', 'Nudibranch', 'Nudibranquio', 'Fionidae', 'Cratena', 'Animalia', '{"seed": true}'::jsonb),
  ('Aplysia fasciata', 'Mottled sea hare', 'Lepre di mare', 'Liebre de mar', 'Aplysiidae', 'Aplysia', 'Animalia', '{"seed": true}'::jsonb),
  ('Bursatella leachii', 'Ragged sea hare', 'Lepre di mare', 'Liebre de mar', 'Aplysiidae', 'Bursatella', 'Animalia', '{"seed": true}'::jsonb),
  ('Ophioderma longicaudum', 'Brittle star', 'Ofiura', 'Ofiura', 'Ophiodermatidae', 'Ophioderma', 'Animalia', '{"seed": true}'::jsonb),
  ('Antedon mediterranea', 'Feather star', 'Comatula', 'Estrella pluma', 'Antedonidae', 'Antedon', 'Animalia', '{"seed": true}'::jsonb),
  ('Marthasterias glacialis', 'Spiny starfish', 'Stella marina spinosa', 'Estrella de mar', 'Asteriidae', 'Marthasterias', 'Animalia', '{"seed": true}'::jsonb),
  ('Echinaster sepositus', 'Red starfish', 'Stella rossa', 'Estrella roja', 'Echinasteridae', 'Echinaster', 'Animalia', '{"seed": true}'::jsonb),
  ('Sphaerechinus granularis', 'Purple sea urchin', 'Riccio viola', 'Erizo violeta', 'Toxopneustidae', 'Sphaerechinus', 'Animalia', '{"seed": true}'::jsonb),
  ('Holothuria tubulosa', 'Sea cucumber', 'Carciofo di mare', 'Pepino de mar', 'Holothuriidae', 'Holothuria', 'Animalia', '{"seed": true}'::jsonb),
  ('Holothuria forskali', 'Black sea cucumber', 'Carciofo nero', 'Pepino de mar', 'Holothuriidae', 'Holothuria', 'Animalia', '{"seed": true}'::jsonb),
  ('Spondylus gaederopus', 'Thorny oyster', 'Spondilo', 'Ostra espinosa', 'Spondylidae', 'Spondylus', 'Animalia', '{"seed": true}'::jsonb),
  ('Charonia tritonis', 'Triton trumpet', 'Tritone', 'Triton', 'Charoniidae', 'Charonia', 'Animalia', '{"seed": true}'::jsonb),
  ('Hexaplex trunculus', 'Dye-murex', 'Murice', 'Canailia', 'Muricidae', 'Hexaplex', 'Animalia', '{"seed": true}'::jsonb),
  ('Haliotis tuberculata', 'Ormer', 'Orecchia di mare', 'Oreja de mar', 'Haliotidae', 'Haliotis', 'Animalia', '{"seed": true}'::jsonb),
  ('Pinna nobilis', 'Noble pen shell', 'Pinna', 'Nacra', 'Pinnidae', 'Pinna', 'Animalia', '{"seed": true}'::jsonb),
  ('Mytilus galloprovincialis', 'Mediterranean mussel', 'Cozza', 'Mejillon', 'Mytilidae', 'Mytilus', 'Animalia', '{"seed": true}'::jsonb),
  ('Spongia officinalis', 'Bath sponge', 'Spugna', 'Esponja', 'Spongiidae', 'Spongia', 'Animalia', '{"seed": true}'::jsonb),
  ('Axinella polypoides', 'Yellow horn sponge', 'Spugna cornuta', 'Esponja', 'Axinellidae', 'Axinella', 'Animalia', '{"seed": true}'::jsonb),
  ('Petrosia ficiformis', 'Elephant ear sponge', 'Spugna orecchia', 'Esponja', 'Petrosiidae', 'Petrosia', 'Animalia', '{"seed": true}'::jsonb),
  ('Aplysina aerophoba', 'Yellow sponge', 'Spugna gialla', 'Esponja amarilla', 'Aplysinidae', 'Aplysina', 'Animalia', '{"seed": true}'::jsonb),
  ('Gobius niger', 'Black goby', 'Gobio nero', 'Gobio negro', 'Gobiidae', 'Gobius', 'Animalia', '{"seed": true}'::jsonb),
  ('Gobius cruentatus', 'Red-mouth goby', 'Gobio', 'Gobio', 'Gobiidae', 'Gobius', 'Animalia', '{"seed": true}'::jsonb),
  ('Parablennius gattorugine', 'Tompot blenny', 'Blennio', 'Blenio', 'Blenniidae', 'Parablennius', 'Animalia', '{"seed": true}'::jsonb),
  ('Tripterygion delaisi', 'Red-black triplefin', 'Tripterigione', 'Tripterigion', 'Tripterygiidae', 'Tripterygion', 'Animalia', '{"seed": true}'::jsonb),
  ('Ctenolabrus rupestris', 'Goldsinny wrasse', 'Tordo', 'Doncella', 'Labridae', 'Ctenolabrus', 'Animalia', '{"seed": true}'::jsonb),
  ('Symphodus roissali', 'Five-spotted wrasse', 'Tordo', 'Doncella', 'Labridae', 'Symphodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Symphodus ocellatus', 'Ocellated wrasse', 'Tordo', 'Doncella', 'Labridae', 'Symphodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Crenilabrus ocellatus', 'Ocellated wrasse', 'Tordo', 'Doncella', 'Labridae', 'Crenilabrus', 'Animalia', '{"seed": true}'::jsonb),
  ('Solea solea', 'Common sole', 'Sogliola', 'Lenguado', 'Soleidae', 'Solea', 'Animalia', '{"seed": true}'::jsonb),
  ('Bothus podas', 'Wide-eyed flounder', 'Passera', 'Lenguado', 'Bothidae', 'Bothus', 'Animalia', '{"seed": true}'::jsonb),
  ('Scophthalmus rhombus', 'Brill', 'Rombo chiodato', 'Rodaballo', 'Scophthalmidae', 'Scophthalmus', 'Animalia', '{"seed": true}'::jsonb),
  ('Psetta maxima', 'Turbot', 'Rombo', 'Rodaballo', 'Scophthalmidae', 'Psetta', 'Animalia', '{"seed": true}'::jsonb),
  ('Trachurus trachurus', 'Horse mackerel', 'Occhiotto', 'Jurel', 'Carangidae', 'Trachurus', 'Animalia', '{"seed": true}'::jsonb),
  ('Caranx crysos', 'Blue runner', 'Carango', 'Jurel', 'Carangidae', 'Caranx', 'Animalia', '{"seed": true}'::jsonb),
  ('Sphyraena viridensis', 'Yellowmouth barracuda', 'Barracuda', 'Barracuda', 'Sphyraenidae', 'Sphyraena', 'Animalia', '{"seed": true}'::jsonb),
  ('Pomatomus saltatrix', 'Bluefish', 'Pesce serra', 'Anjova', 'Pomatomidae', 'Pomatomus', 'Animalia', '{"seed": true}'::jsonb),
  ('Coryphaena hippurus', 'Common dolphinfish', 'Lampuga', 'Dorado', 'Coryphaenidae', 'Coryphaena', 'Animalia', '{"seed": true}'::jsonb),
  ('Trisopterus luscus', 'Pouting', 'Trisoptero', 'Faneca', 'Gadidae', 'Trisopterus', 'Animalia', '{"seed": true}'::jsonb),
  ('Micromesistius poutassou', 'Blue whiting', 'Merlano', 'Merluza', 'Gadidae', 'Micromesistius', 'Animalia', '{"seed": true}'::jsonb),
  ('Phycis phycis', 'Forkbeard', 'Mostella', 'Mostela', 'Phycidae', 'Phycis', 'Animalia', '{"seed": true}'::jsonb),
  ('Arnoglossus laterna', 'Scaldfish', 'Passera', 'Lenguado', 'Bothidae', 'Arnoglossus', 'Animalia', '{"seed": true}'::jsonb),
  ('Pegusa lascaris', 'Sand sole', 'Lingua', 'Lenguado', 'Soleidae', 'Pegusa', 'Animalia', '{"seed": true}'::jsonb),
  ('Platichthys flesus', 'European flounder', 'Passera', 'Platija', 'Pleuronectidae', 'Platichthys', 'Animalia', '{"seed": true}'::jsonb),
  ('Chelidonichthys lucerna', 'Tub gurnard', 'Capone', 'Rubio', 'Triglidae', 'Chelidonichthys', 'Animalia', '{"seed": true}'::jsonb),
  ('Trigla lyra', 'Piper gurnard', 'Capone', 'Rubio', 'Triglidae', 'Trigla', 'Animalia', '{"seed": true}'::jsonb),
  ('Dactylopterus volitans', 'Flying gurnard', 'Pesce volante', 'Pez volador', 'Dactylopteridae', 'Dactylopterus', 'Animalia', '{"seed": true}'::jsonb),
  ('Callionymus lyra', 'Tub gurnard', 'Dragoncello', 'Pez arana', 'Callionymidae', 'Callionymus', 'Animalia', '{"seed": true}'::jsonb),
  ('Capros aper', 'Boarfish', 'Capros', 'Chicharro', 'Caproidae', 'Capros', 'Animalia', '{"seed": true}'::jsonb),
  ('Cepola macrophthalma', 'Red bandfish', 'Cepola', 'Pez cinta', 'Cepolidae', 'Cepola', 'Animalia', '{"seed": true}'::jsonb),
  ('Atherina boyeri', 'Big-scale sand smelt', 'Alletta', 'Chinguillo', 'Atherinidae', 'Atherina', 'Animalia', '{"seed": true}'::jsonb),
  ('Sprattus sprattus', 'European sprat', 'Spratto', 'Espadin', 'Clupeidae', 'Sprattus', 'Animalia', '{"seed": true}'::jsonb),
  ('Belone euxini', 'Black Sea garfish', 'Aguglia', 'Aguja', 'Belonidae', 'Belone', 'Animalia', '{"seed": true}'::jsonb),
  ('Aulostomus strigosus', 'Atlantic trumpetfish', 'Pesce trombetta', 'Pez trompeta', 'Aulostomidae', 'Aulostomus', 'Animalia', '{"seed": true}'::jsonb),
  ('Macroramphosus scolopax', 'Longspine snipefish', 'Pesce becco', 'Pez trompeta', 'Centriscidae', 'Macroramphosus', 'Animalia', '{"seed": true}'::jsonb),
  ('Lagocephalus lagocephalus', 'Oceanic puffer', 'Pesce palla', 'Pez globo', 'Tetraodontidae', 'Lagocephalus', 'Animalia', '{"seed": true}'::jsonb),
  ('Diodon holocanthus', 'Balloonfish', 'Pesce palla', 'Pez globo', 'Diodontidae', 'Diodon', 'Animalia', '{"seed": true}'::jsonb),
  ('Monacanthus ciliatus', 'Fringed filefish', 'Pesce lima', 'Pez lima', 'Monacanthidae', 'Monacanthus', 'Animalia', '{"seed": true}'::jsonb),
  ('Canthidermis maculata', 'Spotted triggerfish', 'Balestra maculata', 'Pez ballesta', 'Balistidae', 'Canthidermis', 'Animalia', '{"seed": true}'::jsonb),
  ('Pterois miles', 'Devil firefish', 'Pesce leone', 'Pez leon', 'Scorpaenidae', 'Pterois', 'Animalia', '{"seed": true}'::jsonb),
  ('Scorpaena notata', 'Small scorpionfish', 'Scorfano piccolo', 'Rascacio', 'Scorpaenidae', 'Scorpaena', 'Animalia', '{"seed": true}'::jsonb),
  ('Ophidion barbatum', 'Bearded cusk-eel', 'Ophidion', 'Ofidio', 'Ophidiidae', 'Ophidion', 'Animalia', '{"seed": true}'::jsonb),
  ('Lepidopus caudatus', 'Silver scabbardfish', 'Pesce lama', 'Pez espada', 'Trichiuridae', 'Lepidopus', 'Animalia', '{"seed": true}'::jsonb),
  ('Aphanopus carbo', 'Black scabbardfish', 'Pesce lama nero', 'Pez espada negro', 'Trichiuridae', 'Aphanopus', 'Animalia', '{"seed": true}'::jsonb),
  ('Istiophorus albicans', 'Atlantic sailfish', 'Pesce vela', 'Pez vela', 'Istiophoridae', 'Istiophorus', 'Animalia', '{"seed": true}'::jsonb),
  ('Makaira nigricans', 'Blue marlin', 'Marlin', 'Marlin azul', 'Istiophoridae', 'Makaira', 'Animalia', '{"seed": true}'::jsonb),
  ('Lamna nasus', 'Porbeagle', 'Squalo mako', 'Marrajo', 'Lamnidae', 'Lamna', 'Animalia', '{"seed": true}'::jsonb),
  ('Isurus oxyrinchus', 'Shortfin mako', 'Squalo mako', 'Mako', 'Lamnidae', 'Isurus', 'Animalia', '{"seed": true}'::jsonb),
  ('Cetorhinus maximus', 'Basking shark', 'Squalo elefante', 'Tiburon peregrino', 'Cetorhinidae', 'Cetorhinus', 'Animalia', '{"seed": true}'::jsonb),
  ('Hexanchus griseus', 'Bluntnose sixgill shark', 'Squalo grigio', 'Tiburon', 'Hexanchidae', 'Hexanchus', 'Animalia', '{"seed": true}'::jsonb),
  ('Etmopterus spinax', 'Velvet belly lanternshark', 'Squalo velluto', 'Tiburon', 'Etmopteridae', 'Etmopterus', 'Animalia', '{"seed": true}'::jsonb),
  ('Gymnura altavela', 'Spiny butterfly ray', 'Pastinaca', 'Raya mariposa', 'Gymnuridae', 'Gymnura', 'Animalia', '{"seed": true}'::jsonb),
  ('Dasyatis pastinaca', 'Common stingray', 'Pastinaca', 'Raya latigo', 'Dasyatidae', 'Dasyatis', 'Animalia', '{"seed": true}'::jsonb),
  ('Torpedo torpedo', 'Common torpedo', 'Triglia di mare', 'Raya electrica', 'Torpedinidae', 'Torpedo', 'Animalia', '{"seed": true}'::jsonb),
  ('Rhinobatos rhinobatos', 'Common guitarfish', 'Razza chitarra', 'Pez guitarra', 'Rhinobatidae', 'Rhinobatos', 'Animalia', '{"seed": true}'::jsonb),
  ('Mobula hypostoma', 'Atlantic devil ray', 'Manta', 'Manta', 'Mobulidae', 'Mobula', 'Animalia', '{"seed": true}'::jsonb),
  ('Pteroplatytrygon violacea', 'Pelagic stingray', 'Pastinaca', 'Raya latigo', 'Dasyatidae', 'Pteroplatytrygon', 'Animalia', '{"seed": true}'::jsonb),
  ('Stenella coeruleoalba', 'Striped dolphin', 'Stenella', 'Delfin listado', 'Delphinidae', 'Stenella', 'Animalia', '{"seed": true}'::jsonb),
  ('Delphinus delphis', 'Common dolphin', 'Delfino comune', 'Delfin comun', 'Delphinidae', 'Delphinus', 'Animalia', '{"seed": true}'::jsonb),
  ('Grampus griseus', 'Risso dolphin', 'Grampo', 'Delfin de Risso', 'Delphinidae', 'Grampus', 'Animalia', '{"seed": true}'::jsonb),
  ('Physeter macrocephalus', 'Sperm whale', 'Capodoglio', 'Cachalote', 'Physeteridae', 'Physeter', 'Animalia', '{"seed": true}'::jsonb),
  ('Balaenoptera physalus', 'Fin whale', 'Balenottera comune', 'Rorcual comun', 'Balaenopteridae', 'Balaenoptera', 'Animalia', '{"seed": true}'::jsonb),
  ('Lithognathus lithognathus', 'White steenbras', 'Mormora', 'Mormora', 'Sparidae', 'Lithognathus', 'Animalia', '{"seed": true}'::jsonb),
  ('Pagellus acarne', 'Axillary seabream', 'Pagello', 'Pargo', 'Sparidae', 'Pagellus', 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus annularis', 'Annular seabream', 'Sarago sparro', 'Sargo', 'Sparidae', 'Diplodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus puntazzo', 'Sharpsnout seabream', 'Sarago pizzuto', 'Sargo', 'Sparidae', 'Diplodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Diplodus cervinus', 'White seabream', 'Sarago cervino', 'Sargo', 'Sparidae', 'Diplodus', 'Animalia', '{"seed": true}'::jsonb),
  ('Spicara smaris', 'Picarel', 'Spicarelo', 'Mendole', 'Sparidae', 'Spicara', 'Animalia', '{"seed": true}'::jsonb),
  ('Spicara maena', 'Blotched picarel', 'Spicarelo', 'Mendole', 'Sparidae', 'Spicara', 'Animalia', '{"seed": true}'::jsonb),
  ('Centracanthus cirrus', 'Picarel', 'Centolabro', 'Mendole', 'Centracanthidae', 'Centracanthus', 'Animalia', '{"seed": true}'::jsonb),
  ('Acanthodoris pilosa', 'Hairy dorid', 'Nudibranch', 'Nudibranquio', 'Onchidorididae', 'Acanthodoris', 'Animalia', '{"seed": true}'::jsonb),
  ('Berghia coerulescens', 'Blue nudibranch', 'Nudibranch', 'Nudibranquio', 'Aeolidiidae', 'Berghia', 'Animalia', '{"seed": true}'::jsonb),
  ('Tethys fimbria', 'Melon sea slug', 'Nudibranch', 'Nudibranquio', 'Tethydidae', 'Tethys', 'Animalia', '{"seed": true}'::jsonb),
  ('Aplysia depilans', 'Depilating sea hare', 'Lepre di mare', 'Liebre de mar', 'Aplysiidae', 'Aplysia', 'Animalia', '{"seed": true}'::jsonb),
  ('Janthina janthina', 'Violet sea-snail', 'Giannetta', 'Caracol violeta', 'Janthinidae', 'Janthina', 'Animalia', '{"seed": true}'::jsonb),
  ('Physalia physalis', 'Portuguese man o war', 'Caravella', 'Carabela portuguesa', 'Physaliidae', 'Physalia', 'Animalia', '{"seed": true}'::jsonb),
  ('Chrysaora hysoscella', 'Compass jellyfish', 'Medusa bussola', 'Medusa brujula', 'Pelagiidae', 'Chrysaora', 'Animalia', '{"seed": true}'::jsonb),
  ('Mnemiopsis leidyi', 'Sea walnut', 'Ctenoforo', 'Ctenoforo', 'Bolinopsidae', 'Mnemiopsis', 'Animalia', '{"seed": true}'::jsonb),
  ('Beroe ovata', 'Ovate comb jelly', 'Ctenoforo', 'Ctenoforo', 'Beroidae', 'Beroe', 'Animalia', '{"seed": true}'::jsonb),
  ('Sargassum vulgare', 'Common gulfweed', 'Sargasso', 'Sargazo', 'Sargassaceae', 'Sargassum', 'Animalia', '{"seed": true}'::jsonb),
  ('Caulerpa prolifera', 'Green algae', 'Caulerpa', 'Caulerpa', 'Caulerpaceae', 'Caulerpa', 'Animalia', '{"seed": true}'::jsonb),
  ('Padina pavonica', 'Peacock tail algae', 'Padina', 'Padina', 'Dictyotaceae', 'Padina', 'Animalia', '{"seed": true}'::jsonb),
  ('Lithophyllum incrustans', 'Encrusting algae', 'Lithophyllum', 'Lithophyllum', 'Corallinaceae', 'Lithophyllum', 'Animalia', '{"seed": true}'::jsonb),
  ('Acetabularia acetabulum', 'Mermaid wineglass', 'Acetabularia', 'Acetabularia', 'Polyphysaceae', 'Acetabularia', 'Animalia', '{"seed": true}'::jsonb),
  ('Halimeda tuna', 'Green calcareous algae', 'Halimeda', 'Halimeda', 'Halimedaceae', 'Halimeda', 'Animalia', '{"seed": true}'::jsonb),
  ('Cystoseira compressa', 'Brown seaweed', 'Cystoseira', 'Cystoseira', 'Sargassaceae', 'Cystoseira', 'Animalia', '{"seed": true}'::jsonb),
  ('Ulva lactuca', 'Sea lettuce', 'Lattuga di mare', 'Lechuga de mar', 'Ulvaceae', 'Ulva', 'Animalia', '{"seed": true}'::jsonb),
  ('Gracilaria gracilis', 'Red algae', 'Gracilaria', 'Gracilaria', 'Gracilariaceae', 'Gracilaria', 'Animalia', '{"seed": true}'::jsonb)
ON CONFLICT (scientific_name) DO UPDATE SET
  common_name = COALESCE(species.common_name, EXCLUDED.common_name),
  common_name_it = COALESCE(species.common_name_it, EXCLUDED.common_name_it),
  common_name_es = COALESCE(species.common_name_es, EXCLUDED.common_name_es),
  family = COALESCE(species.family, EXCLUDED.family),
  genus = COALESCE(species.genus, EXCLUDED.genus),
  updated_at = now();

INSERT INTO operators (name, slug, country_code, operator_type, location, address, email, phone, website, subscription_tier, subscription_status, metadata)
VALUES
  ('Diving Center Ustica', 'diving-center-ustica', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(13.185, 38.705), 4326)::geography, 'Via Cristoforo Colombo 12, Ustica', 'info@divingustica.it', '+39 091 844 9001', 'https://divingustica.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Portofino Divers', 'portofino-divers', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(9.2095, 44.3035), 4326)::geography, 'Via Fondaco 5, Portofino', 'info@portofinodivers.it', '+39 0185 269 012', 'https://portofinodivers.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Elba Sub', 'elba-sub', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(10.321, 42.8145), 4326)::geography, 'Via del Molo 3, Portoferraio', 'info@elbasub.it', '+39 0565 918 234', 'https://elbasub.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Sardinia Dive Experience', 'sardinia-dive-experience', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(9.518, 39.102), 4326)::geography, 'Via Molo Umberto I, Villasimius', 'info@sardiniadive.it', '+39 070 792 456', 'https://sardiniadive.it', 'starter', 'active', '{"seed": true}'::jsonb),
  ('Scuba Academy Siracusa', 'scuba-academy-siracusa', 'IT', 'dive_center', ST_SetSRID(ST_MakePoint(15.29, 37.075), 4326)::geography, 'Lungomare Alfeo 22, Siracusa', 'info@scubaacademy.it', '+39 0931 462 88', 'https://scubaacademy.it', 'starter', 'active', '{"seed": true}'::jsonb)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  email = EXCLUDED.email,
  phone = EXCLUDED.phone,
  website = EXCLUDED.website,
  updated_at = now();

INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'diving-center-ustica' AND ds.slug = 'ustica-secca-colobbara'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'portofino-divers' AND ds.slug = 'ustica-punta-gavazzi'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'elba-sub' AND ds.slug = 'ustica-grotta-gamberi'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'sardinia-dive-experience' AND ds.slug = 'portofino-cristo-abissi'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;
INSERT INTO operator_dive_sites (operator_id, dive_site_id, is_primary)
SELECT o.id, ds.id, true FROM operators o, dive_sites ds
WHERE o.slug = 'scuba-academy-siracusa' AND ds.slug = 'portofino-punta-faro'
ON CONFLICT (operator_id, dive_site_id) DO UPDATE SET is_primary = EXCLUDED.is_primary;

INSERT INTO badges (code, name, description, criteria_type, criteria_value, tier)
VALUES
  ('first-dive', 'First Splash', 'Log your first dive in Benthyo', 'dive_count', '{"count":1}'::jsonb, 1),
  ('ten-dives', 'Deco Disciple', 'Complete 10 logged dives', 'dive_count', '{"count":10}'::jsonb, 1),
  ('fifty-dives', 'Reef Regular', 'Complete 50 logged dives', 'dive_count', '{"count":50}'::jsonb, 2),
  ('hundred-dives', 'Centurion Diver', 'Complete 100 logged dives', 'dive_count', '{"count":100}'::jsonb, 3),
  ('first-species', 'Species Spotter', 'Record your first species sighting', 'species_count', '{"count":1}'::jsonb, 1),
  ('twenty-species', 'Life List Builder', 'See 20 different species', 'species_count', '{"count":20}'::jsonb, 2),
  ('fifty-species', 'Marine Naturalist', 'See 50 different species', 'species_count', '{"count":50}'::jsonb, 3),
  ('five-sites', 'Site Explorer', 'Dive at 5 different sites', 'site_count', '{"count":5}'::jsonb, 1),
  ('med-explorer', 'Mediterranean Explorer', 'Log a dive in the Mediterranean region', 'region', '{"regions":["mediterranean"]}'::jsonb, 2),
  ('group-grouper', 'Grouper Guardian', 'Spot a dusky grouper (Epinephelus marginatus)', 'manual', '{"species":"Epinephelus marginatus"}'::jsonb, 3)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  criteria_type = EXCLUDED.criteria_type,
  criteria_value = EXCLUDED.criteria_value,
  tier = EXCLUDED.tier;

COMMIT;
